version: '3'
services:
  musicapp:
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/app/src
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always

  postgres:
    build:
      context: ./src/db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
