version: '3'
services:
  musicapp:
    build:
      context: ./
    ports:
      - '127.0.0.1:4000:4000'
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    build:
      context: ./docker/db
    networks:
      - app-network

networks:
  app-network:
